CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE public.identity_role (
    id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_identity_role PRIMARY KEY (id)
);

CREATE TABLE public.identity_user (
    id text NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_identity_user PRIMARY KEY (id)
);

CREATE TABLE public.identity_role_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_identity_role_claim PRIMARY KEY (id),
    CONSTRAINT fk_identity_role_claim_identity_role_role_id FOREIGN KEY (role_id) REFERENCES public.identity_role (id) ON DELETE CASCADE
);

CREATE TABLE public.identity_user_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_identity_user_claim PRIMARY KEY (id),
    CONSTRAINT fk_identity_user_claim_identity_user_user_id FOREIGN KEY (user_id) REFERENCES public.identity_user (id) ON DELETE CASCADE
);

CREATE TABLE public.identity_user_login (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT pk_identity_user_login PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_identity_user_login_identity_user_user_id FOREIGN KEY (user_id) REFERENCES public.identity_user (id) ON DELETE CASCADE
);

CREATE TABLE public.identity_user_role (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_identity_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_identity_user_role_identity_role_role_id FOREIGN KEY (role_id) REFERENCES public.identity_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_identity_user_role_identity_user_user_id FOREIGN KEY (user_id) REFERENCES public.identity_user (id) ON DELETE CASCADE
);

CREATE TABLE public.identity_user_token (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_identity_user_token PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_identity_user_token_identity_user_user_id FOREIGN KEY (user_id) REFERENCES public.identity_user (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "RoleNameIndex" ON public.identity_role (normalized_name);

CREATE INDEX ix_identity_role_claim_role_id ON public.identity_role_claim (role_id);

CREATE INDEX "EmailIndex" ON public.identity_user (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON public.identity_user (normalized_user_name);

CREATE INDEX ix_identity_user_claim_user_id ON public.identity_user_claim (user_id);

CREATE INDEX ix_identity_user_login_user_id ON public.identity_user_login (user_id);

CREATE INDEX ix_identity_user_role_role_id ON public.identity_user_role (role_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20240521071537_Initial', '8.0.5');

COMMIT;

